server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.1.27:1433;databaseName=BIZXR_SF_TEST;encrypt=true;trustServerCertificate=true
    username: sa
    password: bizxr12!@

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.erp.**.dto
  configuration:
    map-underscore-to-camel-case: true

app:
  jwt:
    issuer: erp
    secret: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET_32CHARS_MIN"
    access-token-minutes: 60